## UCI Phishing Websites Dataset Exploration

In [1]:
import arff
import polars as pl

In [2]:
with open("../datasets/phishing-websites/Training Dataset.arff", "r") as file:
    dataset = arff.load(file)

In [3]:
dataset.keys()

dict_keys(['description', 'relation', 'attributes', 'data'])

attributes = column names + information about each column

data       = all 11,055 rows

In [5]:
# create the Polars dataframe
column_names = [attribute[0] for attribute in dataset["attributes"]]

df = pl.DataFrame(
    dataset["data"],
    schema=column_names,
    orient="row"
)

df.head()

shape: (5, 31)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ having_IP_ ┆ URL_Length ┆ Shortinin ┆ having_At ┆ … ┆ Google_In ┆ Links_poi ┆ Statistic ┆ Result │
│ Address    ┆ ---        ┆ g_Service ┆ _Symbol   ┆   ┆ dex       ┆ nting_to_ ┆ al_report ┆ ---    │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ page      ┆ ---       ┆ str    │
│ str        ┆            ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ str       ┆           ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ -1         ┆ 1          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ 1         ┆ -1        ┆ -1     │
│ 1          ┆ 1          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ -1     │
│ 1          ┆ 0          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ 0         ┆ -1        ┆ -1     │
│ 1          ┆ 0          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ -1        ┆ 1         ┆ -1     │
│ 1          ┆ 0          ┆ -1        ┆ 1         ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 1      │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [11]:
# convert the columns to integers
df = df.with_columns(
    pl.all().cast(pl.Int64)
)

df.head()

shape: (5, 31)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ having_IP_ ┆ URL_Length ┆ Shortinin ┆ having_At ┆ … ┆ Google_In ┆ Links_poi ┆ Statistic ┆ Result │
│ Address    ┆ ---        ┆ g_Service ┆ _Symbol   ┆   ┆ dex       ┆ nting_to_ ┆ al_report ┆ ---    │
│ ---        ┆ i64        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ page      ┆ ---       ┆ i64    │
│ i64        ┆            ┆ i64       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ i64       ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ -1         ┆ 1          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ 1         ┆ -1        ┆ -1     │
│ 1          ┆ 1          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ -1     │
│ 1          ┆ 0          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ 0         ┆ -1        ┆ -1     │
│ 1          ┆ 0          ┆ 1         ┆ 1         ┆ … ┆ 1         ┆ -1        ┆ 1         ┆ -1     │
│ 1          ┆ 0          ┆ -1        ┆ 1         ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 1      │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [6]:
df.shape

(11055, 31)

In [12]:
df.columns

['having_IP_Address',
 'URL_Length',
 'Shortining_Service',
 'having_At_Symbol',
 'double_slash_redirecting',
 'Prefix_Suffix',
 'having_Sub_Domain',
 'SSLfinal_State',
 'Domain_registeration_length',
 'Favicon',
 'port',
 'HTTPS_token',
 'Request_URL',
 'URL_of_Anchor',
 'Links_in_tags',
 'SFH',
 'Submitting_to_email',
 'Abnormal_URL',
 'Redirect',
 'on_mouseover',
 'RightClick',
 'popUpWidnow',
 'Iframe',
 'age_of_domain',
 'DNSRecord',
 'web_traffic',
 'Page_Rank',
 'Google_Index',
 'Links_pointing_to_page',
 'Statistical_report',
 'Result']

In [14]:
df.schema

Schema([('having_IP_Address', Int64),
        ('URL_Length', Int64),
        ('Shortining_Service', Int64),
        ('having_At_Symbol', Int64),
        ('double_slash_redirecting', Int64),
        ('Prefix_Suffix', Int64),
        ('having_Sub_Domain', Int64),
        ('SSLfinal_State', Int64),
        ('Domain_registeration_length', Int64),
        ('Favicon', Int64),
        ('port', Int64),
        ('HTTPS_token', Int64),
        ('Request_URL', Int64),
        ('URL_of_Anchor', Int64),
        ('Links_in_tags', Int64),
        ('SFH', Int64),
        ('Submitting_to_email', Int64),
        ('Abnormal_URL', Int64),
        ('Redirect', Int64),
        ('on_mouseover', Int64),
        ('RightClick', Int64),
        ('popUpWidnow', Int64),
        ('Iframe', Int64),
        ('age_of_domain', Int64),
        ('DNSRecord', Int64),
        ('web_traffic', Int64),
        ('Page_Rank', Int64),
        ('Google_Index', Int64),
        ('Links_pointing_to_page', Int64),
        ('Statistical_report', Int64),
        ('Result', Int64)])

In [13]:
df.null_count()

shape: (1, 31)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ having_IP_ ┆ URL_Length ┆ Shortinin ┆ having_At ┆ … ┆ Google_In ┆ Links_poi ┆ Statistic ┆ Result │
│ Address    ┆ ---        ┆ g_Service ┆ _Symbol   ┆   ┆ dex       ┆ nting_to_ ┆ al_report ┆ ---    │
│ ---        ┆ u32        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ page      ┆ ---       ┆ u32    │
│ u32        ┆            ┆ u32       ┆ u32       ┆   ┆ u32       ┆ ---       ┆ u32       ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ 0          ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0      │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [15]:
df.group_by("Result").len().sort("Result")

shape: (2, 2)
┌────────┬──────┐
│ Result ┆ len  │
│ ---    ┆ ---  │
│ i64    ┆ u32  │
╞════════╪══════╡
│ -1     ┆ 4898 │
│ 1      ┆ 6157 │
└────────┴──────┘